# Generated by Django 4.1.7 on 2023-03-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imguruser',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
