# Generated by Django 4.1.7 on 2023-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=0, upload_to='images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
