# Generated by Django 4.1.7 on 2023-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0002_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
