# Generated by Django 4.1.7 on 2023-03-10 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0003_like_imguruser_user_alter_imguruser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='like_id',
            new_name='like',
        ),
        migrations.RenameField(
            model_name='subcomment',
            old_name='like_id',
            new_name='like',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('size', models.CharField(max_length=45)),
                ('mimeType', models.CharField(max_length=45)),
                ('path', models.CharField(max_length=90)),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='imgur.post')),
            ],
        ),
    ]
