# Generated by Django 4.1.7 on 2023-03-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0004_rename_like_id_comment_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imguruser',
            name='phone_number',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='imguruser',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
